In [1]:
!ls

4_results.tsv            pandas_scratchbook.ipynb

In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_table('4_results.tsv', sep="\t")

df.head()

   method       dataset  APSI  APSSI       SPS     SCI  braliSCI  uniq  k
0  mafftx  SRP_euk_arch    31     -1  0.167164  0.8495        96     1  2
1  mafftx  SRP_euk_arch    45     -1  0.136054  0.9582        87     1  2
2  mafftx  SRP_euk_arch    36     -1  0.115152  0.5542        77     1  2
3  mafftx  SRP_euk_arch    57     -1  0.218543  1.0035       110     1  2
4  mafftx  SRP_euk_arch    56     -1  0.717608  1.1120       110     2  2

In [3]:
df.shape

(94950, 9)

In [4]:
df.dtypes

method       object
dataset      object
APSI          int64
APSSI         int64
SPS         float64
SCI         float64
braliSCI      int64
uniq          int64
k             int64
dtype: object

In [5]:
print(df.method.unique())
print(df.dataset.unique())
np.unique(np.array([1,1,2,3]))

['mafftx' 'sparse' 'beagles' 'mlocarna' 'raf']
['SRP_euk_arch' 'gcvT' '5_8S_rRNA' 'U6' 'Histone3' 'Entero_OriR' 'S_box'
 'sno_14q_I_II' 'Hammerhead_3' 'Cobalamin' 'TAR' 'Lysine' 'UnaL2'
 'HCV_SLIV' 'Hammerhead_1' 'HIV_FE' 'THI' 'yybP-ykoY' 'T-box' 'HIV_GSL3'
 'tRNA' 'IRES_HCV' 'SRP_bact' 'Entero_5_CRE' 'U1' 'Intron_gpII' 'SECIS'
 'U2' 'Retroviral_psi' 'IRES_Picorna' 'HCV_SLVII' 'HIV_PBS' '5S_rRNA'
 'Entero_CRE' 'K_chan_RES' 'HepC_CRE']

array([1, 2, 3])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94950 entries, 0 to 94949
Data columns (total 9 columns):
method      94950 non-null object
dataset     94950 non-null object
APSI        94950 non-null int64
APSSI       94950 non-null int64
SPS         94950 non-null float64
SCI         94950 non-null float64
braliSCI    94950 non-null int64
uniq        94950 non-null int64
k           94950 non-null int64
dtypes: float64(2), int64(5), object(2)
memory usage: 6.5+ MB

In [7]:
df.describe(include='all')

,method,dataset,APSI,APSSI,SPS,SCI,braliSCI,uniq,k
count,94950,94950,94950.000000,94950.0,94950.000000,94950.000000,94950.000000,94950.000000,94950.000000
unique,5,36,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,beagles,tRNA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,18990,20110,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,68.557504,-1.0,0.595140,0.930547,93.983044,1.652185,3.710321
std,NaN,NaN,19.517234,0.0,0.334326,0.221283,17.189719,1.497587,2.769626
min,NaN,NaN,16.000000,-1.0,0.000000,-0.000000,66.000000,1.000000,2.000000
25%,NaN,NaN,51.000000,-1.0,0.274257,0.817900,80.000000,1.000000,2.000000
50%,NaN,NaN,71.000000,-1.0,0.610781,0.958400,93.000000,1.000000,3.000000
75%,NaN,NaN,87.000000,-1.0,0.957627,1.060100,104.000000,2.000000,5.000000
max,NaN,NaN,95.000000,-1.0,1.000000,2.014000,175.000000,21.000000,15.000000

In [11]:
df.describe?

In [13]:
df.iloc[1:3,0]

1    mafftx
2    mafftx
Name: method, dtype: object

In [14]:
#boolean indexing (how many with SPS over 75%?)
df.sample(10)

,method,dataset,APSI,APSSI,SPS,SCI,braliSCI,uniq,k
10212,mafftx,THI,51,-1,0.307612,0.7537,70,1,7
33833,sparse,U1,52,-1,0.120527,1.0279,68,1,3
62055,mlocarna,tRNA,50,-1,0.932432,1.1782,110,1,2
34988,sparse,Entero_CRE,82,-1,0.770492,0.8161,78,1,3
76700,raf,Hammerhead_3,44,-1,0.603448,1.0795,96,1,2
84761,raf,Entero_CRE,93,-1,1.000000,1.0751,100,2,2
37091,sparse,HIV_PBS,92,-1,0.890909,0.8673,86,1,5
4845,mafftx,tRNA,47,-1,0.263158,1.1027,108,1,2
71398,mlocarna,IRES_HCV,93,-1,0.411609,0.7252,74,1,3
81260,raf,tRNA,51,-1,1.000000,1.0980,110,3,2

In [15]:
#groupby
by_meth = df.groupby('method')
by_meth.mean()

by_meth_ds = df.groupby(['method','dataset'])
by_meth_ds.mean()
##SPS medio per methodo, dataset e APSI

by_meth_APSI = df.groupby(['method','APSI'])
data=by_meth_APSI.SPS.mean()

In [16]:
type(by_meth_APSI.SPS.mean())


data.index

MultiIndex(levels=[['beagles', 'mafftx', 'mlocarna', 'raf', 'sparse'], [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
           labels=[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]],
           names=['method', 'APSI'])

In [17]:
df.mean()

APSI        68.557504
APSSI       -1.000000
SPS          0.595140
SCI          0.930547
braliSCI    93.983044
uniq         1.652185
k            3.710321
dtype: float64

In [18]:
#iterrows, itertuples

# estrai le media SCI per metodo del sottodataframe comprendente le righe con SPS superiore al 50% e APSI inferiore a 0.7

In [19]:
df.head()

   method       dataset  APSI  APSSI       SPS     SCI  braliSCI  uniq  k
0  mafftx  SRP_euk_arch    31     -1  0.167164  0.8495        96     1  2
1  mafftx  SRP_euk_arch    45     -1  0.136054  0.9582        87     1  2
2  mafftx  SRP_euk_arch    36     -1  0.115152  0.5542        77     1  2
3  mafftx  SRP_euk_arch    57     -1  0.218543  1.0035       110     1  2
4  mafftx  SRP_euk_arch    56     -1  0.717608  1.1120       110     2  2

In [38]:
c1 = df.APSI < 70
c2 = df.SCI > 0.5
df[c1&c2].groupby('method').mean()

               APSI  APSSI       SPS       SCI    braliSCI      uniq         k
method
beagles   51.102903   -1.0  0.488935  0.850984  103.134542  1.435263  2.811243
mafftx    50.508346   -1.0  0.536324  0.969146  100.016136  1.374026  3.545960
mlocarna  50.360044   -1.0  0.449450  1.072608   99.675122  1.369624  3.537180
raf       50.356648   -1.0  0.497868  1.074200   99.508662  1.367908  3.549372
sparse    50.342322   -1.0  0.353278  1.062942   99.811137  1.370492  3.522745

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94950 entries, 0 to 94949
Data columns (total 9 columns):
method      94950 non-null object
dataset     94950 non-null object
APSI        94950 non-null int64
APSSI       94950 non-null int64
SPS         94950 non-null float64
SCI         94950 non-null float64
braliSCI    94950 non-null int64
uniq        94950 non-null int64
k           94950 non-null int64
dtypes: float64(2), int64(5), object(2)
memory usage: 6.5+ MB

In [47]:
df[(df.APSI<70) & (df.SCI)>0.5].groupby('method').mean()

               APSI  APSSI       SPS       SCI   braliSCI      uniq         k
method
beagles   50.459560   -1.0  0.403614  0.694312  99.615604  1.371319  3.459451
mafftx    50.352295   -1.0  0.528153  0.951026  99.391403  1.366624  3.560440
mlocarna  50.352295   -1.0  0.446292  1.065733  99.391403  1.366624  3.560440
raf       50.352295   -1.0  0.496898  1.070992  99.391403  1.366624  3.560440
sparse    50.342660   -1.0  0.349696  1.051826  99.457384  1.367290  3.562169

In [46]:
df.loc[(df.APSI<70) & (df.SCI)>0.5]

       method       dataset  APSI  APSSI       SPS     SCI  braliSCI  uniq   k
0      mafftx  SRP_euk_arch    31     -1  0.167164  0.8495        96     1   2
1      mafftx  SRP_euk_arch    45     -1  0.136054  0.9582        87     1   2
2      mafftx  SRP_euk_arch    36     -1  0.115152  0.5542        77     1   2
3      mafftx  SRP_euk_arch    57     -1  0.218543  1.0035       110     1   2
4      mafftx  SRP_euk_arch    56     -1  0.717608  1.1120       110     2   2
5      mafftx  SRP_euk_arch    42     -1  0.615894  0.9806       106     1   2
6      mafftx  SRP_euk_arch    55     -1  0.286195  0.9651       103     1   2
9      mafftx  SRP_euk_arch    59     -1  0.653968  0.9494        98     1   2
10     mafftx  SRP_euk_arch    34     -1  0.243243  0.8020        92     2   2
11     mafftx  SRP_euk_arch    56     -1  0.200000  1.2060       112     1   2
13     mafftx  SRP_euk_arch    28     -1  0.057751  0.8418        80     1   2
17     mafftx  SRP_euk_arch    34     -1  0.062874  0.7826        92     1   2
18     mafftx  SRP_euk_arch    63     -1  0.332258  0.9721        87     1   2
19     mafftx  SRP_euk_arch    39     -1  0.197568  0.7908        99     1   2
20     mafftx  SRP_euk_arch    32     -1  0.108761  0.7415        97     1   2
21     mafftx  SRP_euk_arch    30     -1  0.190909  0.6011        92     2   2
22     mafftx  SRP_euk_arch    36     -1  0.171171  0.8561        99     1   2
23     mafftx  SRP_euk_arch    31     -1  0.065015  0.6985        87     1   2
24     mafftx  SRP_euk_arch    40     -1  0.197568  1.0140        96     1   2
25     mafftx  SRP_euk_arch    41     -1  0.167683  0.8203        92     1   2
26     mafftx  SRP_euk_arch    40     -1  0.212766  0.9267        99     1   2
27     mafftx  SRP_euk_arch    32     -1  0.163142  0.8346        98     1   2
29     mafftx  SRP_euk_arch    56     -1  0.211921  1.0395       110     1   2
30     mafftx  SRP_euk_arch    35     -1  0.216617  0.9147        79     2   2
31     mafftx  SRP_euk_arch    28     -1  0.090909  0.6532        90     1   2
33     mafftx  SRP_euk_arch    39     -1  0.187879  0.9350        95     1   2
34     mafftx  SRP_euk_arch    63     -1  0.818182  1.1348        96     1   2
35     mafftx  SRP_euk_arch    35     -1  0.165663  0.7415        92     1   2
36     mafftx  SRP_euk_arch    63     -1  0.289902  1.0447       103     1   2
37     mafftx  SRP_euk_arch    36     -1  0.179641  0.8259        92     1   2
...       ...           ...   ...    ...       ...     ...       ...   ...  ..
94913     raf       5S_rRNA    56     -1  0.117309  1.0663        67     2  15
94914     raf       5S_rRNA    55     -1  0.532949  1.1448        81     1  15
94915     raf       5S_rRNA    55     -1  0.331413  1.0662        76     1  15
94916     raf       5S_rRNA    56     -1  0.203226  1.0546        70     1  15
94917     raf       5S_rRNA    57     -1  0.138326  1.0542        76     4  15
94918     raf       5S_rRNA    55     -1  0.097158  0.9985        88     1  15
94919     raf       5S_rRNA    56     -1  0.263724  1.2027        94     1  15
94920     raf       5S_rRNA    59     -1  0.137415  0.9361        68     1  15
94921     raf       5S_rRNA    57     -1  0.088249  1.0730        76     2  15
94922     raf       5S_rRNA    57     -1  0.212343  1.0056        76     1  15
94923     raf       5S_rRNA    59     -1  0.726267  1.0150        70     1  15
94924     raf       5S_rRNA    56     -1  0.224000  0.9487        73     1  15
94925     raf       5S_rRNA    56     -1  0.289164  1.1149        83     1  15
94926     raf       5S_rRNA    57     -1  0.626077  0.9399        79     1  15
94927     raf       5S_rRNA    56     -1  0.575176  1.0718        85     1  15
94928     raf       5S_rRNA    56     -1  0.478019  1.0261        73     2  15
94929     raf       5S_rRNA    56     -1  0.159713  0.9198        69     1  15
94930     raf       5S_rRNA    56     -1  0.498586  0.9518        80     1  15
94931     raf       5S_rRNA    54     -1  0.786395  1.0565        95     1  15
94932     raf       5S_rRNA    55     -1  0.473041  0.9977        68     1  15
94933     raf       5S_rRNA    54     -1  0.509751  1.0281        75     1  15
94934     raf       5S_rRNA    57     -1  0.254422  0.9035        77     1  15
94935     raf       5S_rRNA    54     -1  0.608631  1.1409        82     1  15
94936     raf       5S_rRNA    56     -1  0.121198  0.9733        71     1  15
94937     raf       5S_rRNA    56     -1  0.481140  1.0239        75     1  15
94938     raf       5S_rRNA    56     -1  0.086546  1.0439        74     1  15
94939     raf       5S_rRNA    59     -1  0.167829  0.9902        72     1  15
94940     raf       5S_rRNA    60     -1  0.276266  0.9363        72     1  15
94941     raf       5S_rRNA    55     -1  0.097396  0.9847        72     1  15
94942     raf       5S_rRNA    59     -1  0.451103  1.1604        82     1  15

[46203 rows x 9 columns]